In [1]:
import numpy as np

# ReLU

In [4]:
def relu(num):
    return np.maximum(0, num)

In [5]:
relu(10)

10

In [6]:
relu(-10)

0

In [7]:
relu(np.array([-3, 0, 6, 7]))

array([0, 0, 6, 7])

# Leaky ReLU

In [8]:
def leaky_relur(x, alpha=.01):
    return np.where(x > 0, x, x * alpha)

In [9]:
leaky_relur(-6)

array(-0.06)

In [10]:
leaky_relur(np.array([-4, -2, 0, 4, 3]))

array([-0.04, -0.02,  0.  ,  4.  ,  3.  ])

# ELU

In [11]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) -1))

In [12]:
elu(-4)

array(-0.98168436)

In [13]:
elu(np.array([-4, -2, 0, 5, 6]))

array([-0.98168436, -0.86466472,  0.        ,  5.        ,  6.        ])

# Sigmoid

In [14]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [15]:
sigmoid(np.array([-5, -2, 0, 5, 8]))

array([0.00669285, 0.11920292, 0.5       , 0.99330715, 0.99966465])

# Softmax

In [29]:
def softmax(x):
    e_x = np.exp(x)
    return e_x / e_x.sum(axis=0)

In [30]:
softmax(np.array([2, 1, .5]))

array([0.62853172, 0.2312239 , 0.14024438])

# Swish

In [31]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)

In [32]:
swish(5)

4.966535745378576

In [41]:
swish(np.array([-3, 0, 5, 7]))

array([-0.14227762,  0.        ,  4.96653575,  6.99362264])

# Linear

In [34]:
def linear(x):
    return x

In [35]:
linear(23)

23

# Tanh

In [36]:
def tanh(x):
    return np.tanh(x)

In [38]:
tanh(5)

0.9999092042625951

In [39]:
tanh(np.array([-4, -1, 0, 3, 6]))

array([-0.9993293 , -0.76159416,  0.        ,  0.99505475,  0.99998771])